name 'awscli-tiny'
maintainer 'Vasiliy Shakhunov'
maintainer_email 'v.shakhunov@gmail.com'
license 'MIT'
description 'Installs/Configures awscli-tiny'
long_description 'Installs/Configures awscli-tiny'
version '0.1.1'
supports 'ubuntu', '~> 16.04'
supports 'centos', '~> 7.0'
source_url 'https://github.com/webchi/chef-awscli-tiny'
issues_url 'https://github.com/webchi/chef-awscli-tiny/issues'
chef_version '>= 13.0'

depends 'poise-python', '~> 1.7.0'